/* global $ hangmanModel hangmanView phrases*/

var phrases = [
  'Dark horse',
  'Eighty six',
  'Fancy free',
  'Funny farm',
  'Go Dolally',
  'Grand slam',
  'He who can',
  'Hoi polloi',
  'In the bag',
  'In the red',
  'In trouble',
  'Knock back',
  'About face',
  'About turn',
  'Act of God',
  'Action man',
  'Make haste',
  'Sacred cow',
  'Sea change',
  'April fool',
  'Ticked off',
  'Blue blood',
  'Bone up on',
  'Booby trap',
  'Born again',
  'A la carte',
  'Air quotes',
  'All at sea',
  'All in all',
  'Augur well',
  'Baby blues',
  'Been there',
  'Bottle out',
  'Boxing Day',
  'By dint of',
  'Carpe diem',
  'Come clean',
  'Cor blimey',
  'Damp squib',
  'Eat my hat',
  'Faff about',
  'Fathom out',
  'Fobbed off',
  'Upper hand',
  'Giddy goat',
  'Go berserk',
  'Go haywire',
  'Guinea pig',
  'Hard lines',
  'In a trice',
  'Inside out',
  'Touch wood',
  'Lark about',
  'Mal de mer',
  'Moot point',
  'Giddy aunt',
  'Needs must',
  'Nul points',
  'Old codger',
  'Cloud nine',
  'Petty cash',
  'Piping hot',
  'Prime time',
  'Quotations',
  'Raise Cain',
  'Real McCoy',
  'Run a mile',
  'Salad days',
  'Say cheese',
  'Slush fund',
  'Sound bite',
  'Tall story',
  'Nth degree',
  'Top drawer',
  'Up in arms',
  'Urban myth',
  'Vice versa',
  'Wax poetic',
  'Hands down',
  'Young turk',
  'Cordon bleu',
  'The Crapper',
  'First water',
  'First World',
  'Four by two',
  'Fuzzy wuzzy',
  'God is dead',
  'Hit the hay',
  'In stitches',
  'In the buff',
  'In the cart',
  'In the club',
  'Ivory tower',
  'Jerry built',
  'Keep schtum',
  'Khyber pass',
  'Above board',
  'Local derby',
  'Main chance',
  'Make my day',
  'On the dole',
  'Paper tiger',
  'All singing',
  'Play by ear',
  'Put paid to',
  'Sorry sight',
  'Up the duff',
  'White bread',
  'Basket case',
  'Box and Cox',
  'Buckle down',
  'By the book',
  'Abracadabra',
  'Ankle biter',
  'Arms akimbo',
  'Easy as pie',
  'Baby boomer',
  'Baby father',
  'Bandy words',
  'Barking mad',
  'Between you',
  'Booby prize',
  'Break a leg',
  'Browned off',
  'Chick flick',
  'Cold turkey',
  'Cut and run',
  'Dead ringer',
  'Fancy pants',
  'Fast asleep',
  'Filthy rich',
  'Get over it',
  'Get the pip',
  'Hard cheese',
  'Heavy metal',
  'Hocus pocus',
  'An ill wind',
  'In a pickle',
  'In the pink',
  'Keep at bay',
  'Marital aid',
  'Mend fences',
  'Mickey Finn',
  'Mondegreens',
  'Motley crew',
  'Mumbo jumbo',
  'Better half',
  'Nosy parker',
  'On the ball',
  'On your tod',
  'Open season',
  'Peeping Tom',
  'Red herring',
  'Road apples',
  'Round Robin',
  'Shake a leg',
  'Silly Billy',
  'Sleep tight',
  'Sour grapes',
  'Spin doctor',
  'Square meal',
  'Van surfing',
  'Taken aback',
  'Tit for tat',
  'Up the pole',
  'Up to snuff',
  'Upper crust',
  'Upside down',
  'Wax lyrical',
  'Well heeled',
  'Willy nilly',
  'Name is mud',
  'Down at heel',
  'Down the pan',
  'End of story',
  'Fifth column',
  'Generation X',
  'Get the sack',
  'God rot them',
  'Gregory Peck',
  'Happy clappy',
  'Hooray Henry',
  'Hush puppies',
  'Charmed life',
  'In your face',
  'Indian giver',
  'Jimmy Horner',
  'Jimmy Riddle',
  'Just in time',
  'Lager frenzy',
  'Less is more',
  'Men in suits',
  'Mexican wave',
  'My old china',
  'Odds bodkins',
  'Out of sight',
  'Thinking cap',
  'Amber nectar',
  'Savoir faire',
  'Send packing',
  'A sea change',
  'Sexton Blake',
  'Son of a gun',
  'Stand up guy',
  'Good as gold',
  'Backroom boy',
  'Bed of roses',
  'The Big Easy',
  'Booze cruise',
  'Cold comfort',
  'Chew the cud',
  'Come on down',
  'Aid and abet',
  'Bad hair day',
  'Bated breath',
  'Battle royal',
  'Bean counter',
  'Bell the cat',
  'Bog standard',
  'Bunny boiler',
  'By and large',
  'By the board',
  'Cock a snook',
  'Common sense',
  'Cotton on to',
  'Curry favour',
  'Double cross',
  'Double Dutch',
  'Draw a blank',
  'Forlorn hope',
  'Get underway',
  'Go whole hog',
  'Halcyon days',
  'Hard hearted',
  'High and dry',
  'Jack the lad',
  'Jam tomorrow',
  'Jump the gun',
  'Just deserts',
  'Knuckle down',
  'Loose cannon',
  'My old Dutch',
  'Nip and tuck',
  'Old chestnut',
  'On the wagon',
  'Out of sorts',
  'Over the top',
  'Pester power',
  'Preposterous',
  'Purple patch',
  'Quality time',
  'Queer Street',
  'Quid pro quo',
  'Short shrift',
  'Silly season',
  'Smart casual',
  'Stool pigeon',
  'Such is life',
  'Body surfing',
  'Take potluck',
  'Take umbrage',
  'The year dot',
  'Tickled pink',
  'Tie the knot',
  'Toe the line',
  'Touch and go',
  'Tuckered out',
  'Weasel words',
  'When in Rome',
  'Whipping boy',
  'Yellow Peril',
  'How do you do',
  'Done a runner',
  'Double whammy',
  'Everybody out',
  'Good in parts',
  'White as snow',
  'In a quandary',
  'In like Flynn',
  'Abide with me',
  'La dolce vita',
  'Loaf of bread',
  'More fool you',
  'Mutt and Jeff',
  'Pommy bashing',
  'Pony and trap',
  'Primrose path',
  'Rock and roll',
  'San fairy Ann',
  'Shoot through',
  'A sorry sight',
  'Steal a march',
  'Sticky wicket',
  'Busy as a bee',
  'Tout de suite',
  'Word for word',
  'The Big Apple',
  'Bite the dust',
  'Blaze a trail',
  'Rough diamond',
  'Pig in a poke',
  'Bang on about',
  'Be enthralled',
  'Beck and call',
  'Beef and reef',
  'Beggar belief',
  'Beyond belief',
  'Bodice ripper',
  'Bottom drawer',
  'Break the ice',
  'Bums on seats',
  'Butterfingers',
  'Carte blanche',
  'Chaise lounge',
  'Charley horse',
  'Cheek by jowl',
  'Rhyming slang',
  'Coin a phrase',
  'Cold shoulder',
  'Cookie cutter',
  'Dock your pay',
  'Doff your hat',
  'Fait accompli',
  'For the birds',
  'Get your goat',
  'Gild the lily',
  'Glass ceiling',
  'Go pound sand',
  'Good riddance',
  'Hairy eyeball',
  'Hard and fast',
  'No truck with',
  'Hunt and peck',
  'In the offing',
  'In the sticks',
  'Indian summer',
  'Jot or tittle',
  'Kiss and tell',
  'Knock on wood',
  'Knuckle under',
  'Lackadaisical',
  'Latin Phrases',
  'Lo and behold',
  'Love is blind',
  'Market forces',
  'Movable feast',
  'My cup of tea',
  'My giddy aunt',
  'On cloud nine',
  'On the bubble',
  'On the button',
  'On the fiddle',
  'One stop shop',
  'Over a barrel',
  'Over the moon',
  'Pass the buck',
  'Piece of piss',
  'When pigs fly',
  'Plain sailing',
  'Rack and ruin',
  'Rank and file',
  'Rule of thumb',
  'My salad days',
  'Silver bullet',
  'Sloane Ranger',
  'Spend a penny',
  'Stinking rich',
  'Surf and turf',
  'Train surfing',
  'Swing for you',
  'Take the cake',
  'The dark side',
  'Life of Riley',
  'Fits to a tee',
  'Up a gum tree',
  'Talk the talk',
  'Walk the walk',
  'Warts and all',
  'With bells on',
  'By your leave',
  'Which is which',
  'Counting sheep',
  'Down the tubes',
  'Godfrey Daniel',
  'Good Samaritan',
  'Granny dumping',
  'Happy slapping',
  'Horse and cart',
  'Meat and drink',
  'Jack Palancing',
  'Know the ropes',
  'Labour of love',
  'Moaning Minnie',
  'Name and shame',
  'Nip in the bud',
  'Plugged nickel',
  'Off the record',
  'Fast and loose',
  'Pound of flesh',
  'Plates of meat',
  'Power dressing',
  'Pyrric victory',
  'Raspberry tart',
  'Rise and shine',
  'The game is up',
  'Bald as a coot',
  'Dead as a dodo',
  'Truth will out',
  'While you live',
  'Zero tolerance',
  'Auld lang syne',
  'Back the field',
  'Back to basics',
  'Ball and chain',
  'Below the belt',
  'Beyond our ken',
  'Billy no mates',
  'Go by the book',
  'Anchors aweigh',
  'As easy as pie',
  'Happy as Larry',
  'At loggerheads',
  'Below the salt',
  'Binge drinking',
  'Blow your mind',
  'Brownie points',
  'Close quarters',
  'Come a cropper',
  'Come up trumps',
  'Total shambles',
  'Cook the books',
  'Cool Britannia',
  'Darby and Joan',
  'Dash to pieces',
  'Done to a turn',
  'Doom and gloom',
  'Gloom and doom',
  'Eat humble pie',
  'Face the music',
  'Fashion victim',
  'Feeding frenzy',
  'French phrases',
  'The full monty',
  'Get on my wick',
  'The upper hand',
  'Get used to it',
  'Go to the dogs',
  'Gordon Bennett',
  'Hand over fist',
  'Hasta la vista',
  'Hither and yon',
  'Horse feathers',
  'Identity theft',
  'In for a penny',
  'Jump the shark',
  'Kangaroo court',
  'Kettle of fish',
  'Marry in haste',
  'Might and main',
  'Morbid obesity',
  'Morning person',
  'Mother country',
  'My better half',
  'On tenterhooks',
  'On the warpath',
  'Panic stations',
  'Penny dreadful',
  'Penny pinching',
  'Pie in the sky',
  'Pigs might fly',
  'Poetic justice',
  'Point to point',
  'Pull up stakes',
  'The real McCoy',
  'Red letter day',
  'Riding shotgun',
  'Senior citizen',
  'Spick and span',
  'Spitting image',
  'Spring forward',
  'Swing the lead',
  'The bitter end',
  'The last straw',
  'Thick and thin',
  'Tissue of lies',
  'The nth degree',
  'Tooth and nail',
  'Trick or treat',
  'Turn of phrase',
  'Turn up trumps',
  'Vicious circle',
  'Walk the plank',
  'Watching brief',
  'White elephant',
  'Win hands down',
  'Woe betide you',
  'Worse for wear',
  'Crocodile tears',
  'Dead cat bounce',
  'Fall from grace',
  'Flesh and blood',
  'Fly on the wall',
  'Forbidden fruit',
  'An axe to grind',
  'History is bunk',
  'In my minds eye',
  'Learn the ropes',
  'Ace in the hole',
  'Rabbit and pork',
  'Shit for brains',
  'Shot in the arm',
  'Angry young man',
  'Take the Mickey',
  'Apple pie order',
  'Turn the tables',
  'Two cents worth',
  'Fit as a fiddle',
  'As good as gold',
  'Wild and woolly',
  'Belt and braces',
  'Bought the farm',
  'Bun in the oven',
  'On Carey Street',
  'Charm offensive',
  'Chinless wonder',
  'Chop and change',
  'A pig in a poke',
  'All of a sudden',
  'All you can eat',
  'Daft as a brush',
  'Happy as a clam',
  'Keen as mustard',
  'Badger to death',
  'Bag and baggage',
  'Baptism of fire',
  'Beyond the pale',
  'Bite the bullet',
  'Go by the board',
  'Canteen culture',
  'Cogito ergo sum',
  'Cop an attitude',
  'Cut the mustard',
  'Deus ex machina',
  'Fair and square',
  'Fits and starts',
  'Give no quarter',
  'Go for a burton',
  'Graveyard shift',
  'Grind to a halt',
  'Have an inkling',
  'Head over heels',
  'Hedge your bets',
  'High and mighty',
  'High on the hog',
  'Household words',
  'If the cap fits',
  'In the doghouse',
  'In the doldrums',
  'Jack in the box',
  'Stiff upper lip',
  'Kick the bucket',
  'Kick your heels',
  'Kilroy was here',
  'Lick into shape',
  'Mad as a hatter',
  'Magical realism',
  'Merry Christmas',
  'No holds barred',
  'Off his own bat',
  'Pig and whistle',
  'Put a damper on',
  'On queer street',
  'Queer the pitch',
  'Run of the mill',
  'Spill the beans',
  'Stone the crows',
  'Stranger danger',
  'Channel surfing',
  'The land of nod',
  'Tongue in cheek',
  'Under the thumb',
  'Whipper snapper',
  'Ethnic cleansing',
  'Excuse my French',
  'Fellow traveller',
  'Go out on a limb',
  'As white as snow',
  'Hold your horses',
  'In the limelight',
  'Join the colours',
  'Like the Dickens',
  'My husband and I',
  'One for the road',
  'Put a sock in it',
  'Put your back up',
  'Ring the changes',
  'Run out of steam',
  'Sex and shopping',
  'Shot in the dark',
  'Skin and blister',
  'Take a back seat',
  'Technicolor yawn',
  'The third degree',
  'Brown as a berry',
  'As busy as a bee',
  'Up a blind alley',
  'Seen better days',
  'Old as the hills',
  'Blonde bombshell',
  'A bunch of fives',
  'Clear blue water',
  'The collywobbles',
  'Load of cobblers',
  'Across the board',
  'Annus horribilis',
  'An arm and a leg',
  'Pleased as Punch',
  'Beg the question',
  'To beggar belief',
  'Biblical phrases',
  'Bury the hatchet',
  'Butter side down',
  'Carbon footprint',
  'Cash on the nail',
  'Chalk and cheese',
  'Champ at the bit',
  'Chinese whispers',
  'Cloak and dagger',
  'Clutch at straws',
  'Cut to the chase',
  'Daylight robbery',
  'Designer stubble',
  'The Devil to pay',
  'Dreams of empire',
  'Fair to middling',
  'Fish or cut bait',
  'Flash in the pan',
  'For good measure',
  'No quarter given',
  'Go the whole hog',
  'Grasp the nettle',
  'Guts for garters',
  'Heavens to Betsy',
  'Hot on the heels',
  'If the shoe fits',
  'In a cleft stick',
  'Know your onions',
  'Living daylights',
  'Nautical phrases',
  'A nest of vipers',
  'Ducks and drakes',
  'Rack your brains',
  'Rub of the green',
  'Run rings around',
  'Run the gauntlet',
  'Watch the birdie',
  'Security blanket',
  'Sent to Coventry',
  'Shaggy dog story',
  'Show your mettle',
  'Sleep like a top',
  'Squeaky bum time',
  'Steal my thunder',
  'Stick in the mud',
  'Talk to the hand',
  'Third time lucky',
  'Turn a blind eye',
  'Wild goose chase',
  'Let or hindrance',
  'The Yellow Peril',
  'Your name is mud',
  'How now brown cow',
  'What are you like',
  'The crack of doom',
  'Differently abled',
  'Drink like a fish',
  'Far be it from me',
  'Foam at the mouth',
  'Give up the ghost',
  'Good men and true',
  'Hot off the press',
  'Jobs for the boys',
  'Katy bar the door',
  'Keep your chin up',
  'Beer and skittles',
  'Against the grain',
  'Multitude of sins',
  'Off with his head',
  'An Oxford scholar',
  'Play it again Sam',
  'Richard the Third',
  'Twenty four seven',
  'An eye for an eye',
  'A shot in the arm',
  'Smoke and mirrors',
  'The game is afoot',
  'As bald as a coot',
  'Cold as any stone',
  'As dead as a dodo',
  'Tower of strength',
  'Wear the trousers',
  'Whistle and flute',
  'Nice as ninepence',
  'Old as Methuselah',
  'The bread of life',
  'Age before beauty',
  'Agree to disagree',
  'Alive and kicking',
  'If you think that',
  'Two peas in a pod',
  'As happy as Larry',
  'As safe as houses',
  'Straight as a die',
  'As the crow flies',
  'At one fell swoop',
  'Bane of your life',
  'Belle of the ball',
  'Blood and thunder',
  'Bricks and clicks',
  'Broad in the beam',
  'Bubble and squeak',
  'Cherchez la femme',
  'Cloud cuckoo land',
  'Complete shambles',
  'Dog in the manger',
  'Dollars to donuts',
  'Roasted to a turn',
  'Down in the dumps',
  'Gone for a burton',
  'Grandfather clock',
  'Greased lightning',
  'Grist to the mill',
  'The hairy eyeball',
  'Harbinger of doom',
  'Joined at the hip',
  'Jury is still out',
  'Left in the lurch',
  'Let them eat cake',
  'Like the clappers',
  'Long in the tooth',
  'Lose your marbles',
  'Middle for diddle',
  'Not my cup of tea',
  'On your beam ends',
  'Push the boat out',
  'Push the envelope',
  'Put up your dukes',
  'Read the riot act',
  'Saved by the bell',
  'Shiver my timbers',
  'Silence is golden',
  'Talk of the Devil',
  'Spitting feathers',
  'Stand and deliver',
  'Strait and narrow',
  'Sweet Fanny Adams',
  'Storm in a teacup',
  'The law is an ass',
  'The life of Riley',
  'Toast of the town',
  'The whole shebang',
  'To the nth degree',
  'We are not amused',
  'Give a wide berth',
  'Keep a wide berth',
  'Winter drawers on',
  'Is the Pope Polish',
  'Fall on your sword',
  'Finger lickin good',
  'For ever and a day',
  'Game of two halves',
  'Thorn in the flesh',
  'Laugh like a drain',
  'Let your hair down',
  'Meet your Waterloo',
  'Middle of the road',
  'Much of a muchness',
  'One over the eight',
  'Press into service',
  'Prick up your ears',
  'Stiffen the sinews',
  'Tickle the ivories',
  'Cool as a cucumber',
  'To be or not to be',
  'Trouble and strife',
  'As fit as a fiddle',
  'The back of beyond',
  'Between two stools',
  'Bolt from the blue',
  'Hell or high water',
  'Lick and a promise',
  'A load of cobblers',
  'According to Hoyle',
  'As daft as a brush',
  'Dead as a doornail',
  'As happy as a clam',
  'Happy as a sandboy',
  'As keen as mustard',
  'Back to square one',
  'Bats in the belfry',
  'Bee in your bonnet',
  'Bells and whistles',
  'Brand spanking new',
  'By the short hairs',
  'Load of codswallop',
  'Come what come may',
  'Compassion fatigue',
  'Fingers and thumbs',
  'Flotsam and jetsam',
  'Fly off the handle',
  'A foot in the door',
  'You get on my wick',
  'Get the upper hand',
  'Get your dander up',
  'Act the giddy goat',
  'Going for a burton',
  'Green eyed monster',
  'Have no truck with',
  'Not rocket science',
  'Jack of all trades',
  'Johnny on the spot',
  'Last but not least',
  'Let there be light',
  'Like it or lump it',
  'As mad as a hatter',
  'Many happy returns',
  'Movers and shakers',
  'Shakers and movers',
  'No laughing matter',
  'On with the motley',
  'Paint the town red',
  'Play the race card',
  'Draw your horns in',
  'Pull in your horns',
  'Pull your horns in',
  'Put the mockers on',
  'Raze to the ground',
  'Play silly buggers',
  'Speak of the Devil',
  'Start from scratch',
  'Stuff and nonsense',
  'The great unwashed',
  'The powers that be',
  'The usual suspects',
  'Throw in the towel',
  'To the manner born',
  'Whet your appetite',
  'Wish you were here',
  'A word in edgeways',
  'Cat got your tongue',
  'Dance attendance on',
  'Darling buds of May',
  'A drop in the ocean',
  'Dropping like flies',
  'For crying out loud',
  'Foregone conclusion',
  'Have a Captain Cook',
  'Keep your pecker up',
  'Level playing field',
  'The fat of the land',
  'My cup runneth over',
  'Play fast and loose',
  'Politically correct',
  'Sold down the river',
  'Some are born great',
  'Strain at the leash',
  'The Devil Incarnate',
  'As brown as a berry',
  'Thou shalt not kill',
  'Three score and ten',
  'Twenty three skidoo',
  'Wet behind the ears',
  'Mad as a march hare',
  'As old as the hills',
  'In the catbird seat',
  'As pleased as Punch',
  'The bane of my life',
  'Best bib and tucker',
  'By hook or by crook',
  'Cock and bull story',
  'The cut of your jib',
  'Driving while black',
  'A fish out of water',
  'Flavor of the month',
  'Fly in the ointment',
  'From pillar to post',
  'Take the upper hand',
  'Play the giddy goat',
  'Got my mojo working',
  'Brook no truck with',
  'In the nick of time',
  'Nice kettle of fish',
  'Make no bones about',
  'Mind your Ps and Qs',
  'No man is an island',
  'Once in a blue moon',
  'Pearls before swine',
  'Pennies from heaven',
  'Piece of the action',
  'Pop goes the weasel',
  'A red rag to a bull',
  'Rest on his laurels',
  'At sixes and sevens',
  'Tempest in a teapot',
  'The apple of my eye',
  'The buck stops here',
  'Words ending in gry',
  'Is the Pope Catholic',
  'Which witch is which',
  'A drop in the bucket',
  'Fight the good fight',
  'Friday afternoon car',
  'Fruits of your loins',
  'Go to the mattresses',
  'Shot across the bows',
  'Have an axe to grind',
  'If I had my druthers',
  'Keep your powder dry',
  'Laid out in lavender',
  'Absent without leave',
  'Lions led by donkeys',
  'Moving the goalposts',
  'New kid on the block',
  'Not worth the candle',
  'Pears for your heirs',
  'All things must pass',
  'A safe pair of hands',
  'Say goodnight Gracie',
  'The call of the wild',
  'Method in my madness',
  'As cold as any stone',
  'Cast the first stone',
  'Vanish into thin air',
  'We are a grandmother',
  'As nice as ninepence',
  'As old as Methuselah',
  'The balance of power',
  'The balance of trade',
  'Beast with two backs',
  'Beat a hasty retreat',
  'Bowled a maiden over',
  'Diamond in the rough',
  'A diamond is forever',
  'Another think coming',
  'As straight as a die',
  'Beat around the bush',
  'Blown to smithereens',
  'Bring home the bacon',
  'Call a spade a spade',
  'A load of codswallop',
  'Brass monkey weather',
  'Dressed to the nines',
  'Elephant in the room',
  'Fight fire with fire',
  'Full to the gunwales',
  'To gild refined gold',
  'Hell in a handbasket',
  'Keep your nose clean',
  'Life begins at forty',
  'Go like the clappers',
  'The living daylights',
  'Look before you leap',
  'My stars and garters',
  'Red sky at night ...',
  'Reduplicated phrases',
  'Special relationship',
  'I will swing for you',
  'The whole nine yards',
  'Tilting at windmills',
  'You are what you eat',
  'No more cakes and ale',
  'Exceedingly well read',
  'A foregone conclusion',
  'Go and boil your head',
  'I bear a charmed life',
  'Lamb to the slaughter',
  'Loose lips sink ships',
  'Age cannot wither her',
  'Not tonight Josephine',
  'Ring down the curtain',
  'Share and share alike',
  'The die has been cast',
  'As cool as a cucumber',
  'Brummagem screwdriver',
  'Blot on the landscape',
  'Blow your own trumpet',
  'A little bird told me',
  'A sight for sore eyes',
  'Accidents will happen',
  'Cost an arm and a leg',
  'As dead as a doornail',
  'As happy as a sandboy',
  'Away with the fairies',
  'Behind the eight ball',
  'The belle of the ball',
  'The camera cannot lie',
  'Chip on your shoulder',
  'Christmas card verses',
  'Cockney rhyming slang',
  'Delusions of grandeur',
  'Flogging a dead horse',
  'A fly in the ointment',
  'Freezing temperatures',
  'Handbags at ten paces',
  'Heavens to Murgatroyd',
  'If wishes were horses',
  'Jump on the bandwagon',
  'The jury is still out',
  'Keep the ball rolling',
  'Keep your hands clean',
  'Pretty kettle of fish',
  'Live long and prosper',
  'Lock stock and barrel',
  'Paddle your own canoe',
  'A piece of the action',
  'Play ducks and drakes',
  'Raining cats and dogs',
  'Red in tooth and claw',
  'Rob Peter to pay Paul',
  'The salt of the earth',
  'The ends of the earth',
  'The toast of the town',
  'Think outside the box',
  'Turn up for the books',
  'Whistle down the wind',
  'Eat drink and be merry',
  'Like a moth to a flame',
  'Much Ado about Nothing',
  'Neither here nor there',
  'No rest for the wicked',
  'Physician heal thyself',
  'Set your teeth on edge',
  'One small step for man',
  'Take down a peg or two',
  'Though this be madness',
  'As mad as a March hare',
  'Bet your bottom dollar',
  'A diamond in the rough',
  'Like two peas in a pod',
  'Snug as a bug in a rug',
  'Better late than never',
  'Chip off the old block',
  'Comparisons are odious',
  'All fingers and thumbs',
  'Packed to the gunwales',
  'Handle with kid gloves',
  'Hit the ground running',
  'Climb on the bandwagon',
  'Keep a stiff upper lip',
  'Let bygones be bygones',
  'Mutton dressed as lamb',
  'No room to swing a cat',
  'On a hiding to nothing',
  'On a wing and a prayer',
  'Preaching to the choir',
  'Pull out all the stops',
  'The quick and the dead',
  'Read between the lines',
  'Neither fish nor flesh',
  'Skeleton in the closet',
  'Sleep on a clothesline',
  'Tell it to the marines',
  'The birds and the bees',
  'Through thick and thin',
  'Keep it under your hat',
  'We know where you live',
  'Win one for the Gipper',
  'Get a word in edgeways',
  'A dish fit for the gods',
  'Drummed out of the army',
  'A nation of shopkeepers',
  'Extraordinary rendition',
  'A fate worse than death',
  'Lay it on with a trowel',
  'Living on borrowed time',
  'All present and correct',
  'Survival of the fittest',
  'The ants are my friends',
  'The road less travelled',
  'There is no alternative',
  'Till the cows come home',
  'To cast the first stone',
  'Tomorrow is another day',
  'Up the apples and pears',
  'Vorsprung Durch Technik',
  'Accidentally on purpose',
  'Pure as the driven snow',
  'Batten down the hatches',
  'Cheap at half the price',
  'Cut off without a penny',
  'Fifteen minutes of fame',
  'The fly in the ointment',
  'For whom the bell tolls',
  'Forewarned is forearmed',
  'From sea to shining sea',
  'Get down to brass tacks',
  'Get off your high horse',
  'Great minds think alike',
  'Hard cases make bad law',
  'Caught in a cleft stick',
  'Knock into a cocked hat',
  'More bang for your buck',
  'Your money or your life',
  'Suspension of disbelief',
  'A turn up for the books',
  'Daniel come to judgement',
  'Get thee behind me Satan',
  'Rose is a rose is a rose',
  'I spy with my little eye',
  'Keep up with the Joneses',
  'A man after my own heart',
  'Out of the jaws of death',
  'Put on your thinking cap',
  'Put the wood in the hole',
  'The tail wagging the dog',
  'The moving finger writes',
  'Too much of a good thing',
  'Twelve good men and true',
  'We have seen better days',
  'Queer as a nine bob note',
  'Beauty is only skin deep',
  'Burning the midnight oil',
  'Different kettle of fish',
  'All intents and purposes',
  'Beware the Ides of March',
  'Carry coals to Newcastle',
  'Curiosity killed the cat',
  'The elephant in the room',
  'Hit the nail on the head',
  'Knight in shining armour',
  'Full of piss and vinegar',
  'Wave a red rag to a bull',
  'See a pin and pick it up',
  'A skeleton in the closet',
  'Gilt off the gingerbread',
  'Three sheets to the wind',
  'To big for your breeches',
  'Trip the light fantastic',
  'Without let or hindrance',
  'Women and children first',
  'How are the mighty fallen',
  'Economical with the truth',
  'Faith will move mountains',
  'Four corners of the earth',
  'From strength to strength',
  'Get off on the wrong foot',
  'I have not slept one wink',
  'Never knowingly undersold',
  'Once more unto the breach',
  'Sealed with a loving kiss',
  'Word association football',
  'Barking up the wrong tree',
  'By the skin of your teeth',
  'Miss is as good as a mile',
  'As snug as a bug in a rug',
  'Back to the drawing board',
  'Bill Stickers is innocent',
  'Black sheep of the family',
  'Caught by the short hairs',
  'Elementary my dear Watson',
  'Fiddling while Rome burns',
  'Make a clean breast of it',
  'Take with a grain of salt',
  'A watched pot never boils',
  'A Daniel come to judgement',
  'Far from the madding crowd',
  'A rose is a rose is a rose',
  'A hard man is good to find',
  'In the twinkling of an eye',
  'It is meat and drink to me',
  'Make a virtue of necessity',
  'Never the twain shall meet',
  'Not worth a plugged nickel',
  'On the shoulders of giants',
  'Put a spanner in the works',
  'Put on the wooden overcoat',
  'Put your nose out of joint',
  'Verbosity leads to unclear',
  'As good luck would have it',
  'When the shit hits the fan',
  'Bury your head in the sand',
  'A different kettle of fish',
  'A good man is hard to find',
  'Alike as two peas in a pod',
  'As pure as the driven snow',
  'Blood toil tears and sweat',
  'The short end of the stick',
  'Famous for fifteen minutes',
  'The floozie in the jacuzzi',
  'Have your guts for garters',
  'Hoist with your own petard',
  'Honesty is the best policy',
  'The whole kit and caboodle',
  'A knight in shining armour',
  'Let the cat out of the bag',
  'Sandwich short of a picnic',
  'Put your best foot forward',
  'Tattoo phrases and sayings',
  'The writing is on the wall',
  'Has the cat got your tongue',
  'Eaten out of house and home',
  'Eye of newt and toe of frog',
  'Make your hair stand on end',
  'In an interesting condition',
  'It never rains but it pours',
  'Keep body and soul together',
  'Pass over to the other side',
  'Pour oil on troubled waters',
  'The Devil take the hindmost',
  'What a piece of work is man',
  'As queer as a nine bob note',
  'The blind leading the blind',
  'Blood is thicker than water',
  'A miss is as good as a mile',
  'A stitch in time saves nine',
  'To all intents and purposes',
  'Ashes to ashes dust to dust',
  'Devil and the deep blue sea',
  'Chickens come home to roost',
  'Elvis has left the building',
  'Fish rot from the head down',
  'Go over like a lead balloon',
  'Wooden hill to Bedfordshire',
  'When it comes to the crunch',
  'The customer is always right',
  'A plague on both your houses',
  'If music be the food of love',
  'Let a thousand flowers bloom',
  'Not playing with a full deck',
  'Point Percy at the porcelain',
  'Shuffle off this mortal coil',
  'For all intents and purposes',
  'Burn the candle at both ends',
  'Fall off the back of a lorry',
  'As fast as greased lightning',
  'Grinning like a Cheshire cat',
  'Hair of the dog that bit you',
  'Innocent until proven guilty',
  'Many a little makes a mickle',
  'Not for all the tea in China',
  'Penny wise and pound foolish',
  'Pull the wool over your eyes',
  'Strike while the iron is hot',
  'Go to the foot of our stairs',
  'Throw your hat into the ring',
  'Something for the weekend sir',
  'Know which way the wind blows',
  'Nothing succeeds like success',
  'Three strikes and you are out',
  'Beat swords into ploughshares',
  'As alike as two peas in a pod',
  'Fine words butter no parsnips',
  'Going to hell in a handbasket',
  'Make hay while the sun shines',
  'Nail your colours to the mast',
  'Put the cart before the horse',
  'A sledgehammer to crack a nut',
  'Time and tide wait for no man',
  'Two heads are better than one',
  'He will give the Devil his due',
  'Living off the fat of the land',
  'Praying at the porcelain altar',
  'Scuse me while I kiss this guy',
  'The smallest room in the house',
  'Wear your heart on your sleeve',
  'A golden key can open any door',
  'Beware of Greeks bearing gifts',
  'A fish rots from the head down',
  'Heard it through the grapevine',
  'One sandwich short of a picnic',
  'Ship shape and Bristol fashion',
  'There but for the grace of God',
  'Truth is stranger than fiction',
  'Up shit creek without a paddle',
  'The early bird catches the worm',
  'Even at the turning of the tide',
  'All things come to he who waits',
  'Excuse me while I kiss this guy',
  'Take the bit between your teeth',
  'A rolling stone gathers no moss',
  'A rolling stone gathers no moss',
  'Between a rock and a hard place',
  'The chickens come home to roost',
  'Every cloud has a silver lining',
  'All publicity is good publicity',
  'Keep your nose to the grindstone',
  'Man does not live by bread alone',
  'The pot calling the kettle black',
  'Quicker than lager turns to piss',
  'A riddle wrapped up in an enigma',
  'Things that go bump in the night',
  'As different as chalk and cheese',
  'The hair of the dog that bit you',
  'Before you can say Jack Robinson',
  'There are three kinds of lies...',
  'Someone is walking over my grave',
  'For every thing there is a season',
  'It came like a bolt from the blue',
  'A leopard cannot change its spots',
  'Never give a sucker an even break',
  'Spare the rod and spoil the child',
  'Birds of a feather flock together',
  'He who laughs last laughs longest',
  'May you live in interesting times',
  'Separate the sheep from the goats',
  'Take the gilt off the gingerbread',
  'A thing of beauty is a joy forever',
  'Like being savaged by a dead sheep',
  'Many are called but few are chosen',
  'Neither a borrower nor a lender be',
  'Born within the sound of Bow Bells',
  'Abandon all hope ye who enter here',
  'Absolute power corrupts absolutely',
  'Many a true word is spoken in jest',
  'Speak softly and carry a big stick',
  'The pen is mightier than the sword',
  'Up the wooden hill to Bedfordshire',
  'Without so much as a by your leave',
  'I will wear my heart upon my sleeve',
  'Mighty oaks from little acorns grow',
  'Now is the winter of our discontent',
  'Standing on the shoulders of giants',
  'Religion is the opium of the people',
  'Richard of York gave battle in vain',
  'A friend in need is a friend indeed',
  'A picture is worth a thousand words',
  'Absence makes the heart grow fonder',
  'The exception which proves the rule',
  'The triumph of hope over experience',
  'Pull yourself up by your bootstraps',
  'Using a sledgehammer to crack a nut',
  'Cut off your nose to spite your face',
  'Like a chicken with its head cut off',
  'Thus far into the bowels of the land',
  'A fool and his money are soon parted',
  'An apple a day keeps the doctor away',
  'Beauty is in the eye of the beholder',
  'Close your eyes and think of England',
  'Never look a gift horse in the mouth',
  'Necessity is the mother of invention',
  'Sticks and stones may break my bones',
  'Hell has no fury like a woman scorned',
  'Let not the sun go down on your wrath',
  'Beelzebub has a devil for a sideboard',
  'Bread always falls buttered side down',
  'Children should be seen and not heard',
  'The best laid schemes of mice and men',
  'The love that dare not speak its name',
  'Is this a dagger which I see before me',
  'Cry havoc and let slip the dogs of war',
  'A ministering angel shall my sister be',
  'Nothing is certain but death and taxes',
  'I have nothing to declare but my genius',
  'Season of mists and mellow fruitfulness',
  'The face that launched a thousand ships',
  'Uneasy lies the head that wears a crown',
  'A little knowledge is a dangerous thing',
  'Between the Devil and the deep blue sea',
  'Out of the mouths of babes and sucklings',
  'Screw your courage to the sticking place',
  'A little of what you fancy does you good',
  'The darkest hour is just before the dawn',
  'Fools rush in where angels fear to tread',
  'Beat the living daylights out of someone',
  'There is more than one way to kill a cat',
  'Here lies one whose name is writ in water',
  'To boldly go where no man has gone before',
  'If the mountain will not come to Muhammad',
  'The proof of the pudding is in the eating',
  'A countenance more in sorrow than in anger',
  'Forgive them for they know not what they do',
  'A house divided against itself cannot stand',
  'A bird in the hand is worth two in the bush',
  'Imitation is the sincerest form of flattery',
  'I see you stand like greyhounds in the slips',
  'Music has charms to soothe the savage breast',
  'The course of true love never did run smooth',
  'A rose by any other name would smell as sweet',
  'A chain is only as strong as its weakest link',
  'Misery acquaints a man with strange bedfellows',
  'A woman needs a man like a fish needs a bicycle',
  'Do unto others as you would have them do to you',
  'Give a man a fish and you will feed him for a day',
  'A place for everything and everything in its place',
  'More honoured in the breach than in the observance',
  'Cold enough to freeze the balls off a brass monkey',
  'Early to bed and early to rise makes a man healthy',
  'What God has joined together let no man put asunder',
  'A man who is his own lawyer has a fool for a client',
  'To travel hopefully is a better thing than to arrive',
  'The female of the species is more deadly then the male',
  'I have nothing to offer but blood toil tears and sweat',
  'Better to have loved and lost than never to have loved at all',
  'Take care of the pence and the pounds will take care of themselves'
  ]
